---
include:
  # Modified existing builds - make them peripherals for dongle use
  - board: eyelash_sofle_left
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: eyelash_sofle_left_peripheral
  
  - board: eyelash_sofle_right
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: eyelash_sofle_right_peripheral
  
  # Dongle build with ZMK Studio support
  - board: nice_nano_v2
    shield: eyelash_sofle_dongle nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_dongle_studio
  
  # Keep your original Studio build for non-dongle use if needed
  - board: eyelash_sofle_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_sofle_studio_left_standalone
  
  # Settings reset
  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset_left
  
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_dongle
