file_format: "1"
id: eyelash_sofle_dongle
name: "Eyelash Sofle Dongle"
type: shield
url: https://github.com/austingavent/zmk-sofle
requires: [pro_micro]
features:
  - keys
siblings:
  - eyelash_sofle_left
  - eyelash_sofle_right
